import type { Category } from '../types'

export interface PopularService {
  name: string
  cat: Category
}

export const POPULAR_SERVICES: PopularService[] = [
  { name: 'Netflix', cat: 'Entertainment' },
  { name: 'Disney+', cat: 'Entertainment' },
  { name: 'HBO Max', cat: 'Entertainment' },
  { name: 'Hulu', cat: 'Entertainment' },
  { name: 'Paramount+', cat: 'Entertainment' },
  { name: 'Crunchyroll', cat: 'Entertainment' },
  { name: 'Audible', cat: 'Entertainment' },
  { name: 'YouTube Premium', cat: 'Entertainment' },
  { name: 'Spotify', cat: 'Music' },
  { name: 'Apple Music', cat: 'Music' },
  { name: 'YouTube Music', cat: 'Music' },
  { name: 'Tidal', cat: 'Music' },
  { name: 'SoundCloud Go', cat: 'Music' },
  { name: 'The New York Times', cat: 'News' },
  { name: 'The Economist', cat: 'News' },
  { name: 'The Wall Street Journal', cat: 'News' },
  { name: 'Medium', cat: 'News' },
  { name: 'Planet Fitness', cat: 'Fitness' },
  { name: 'Peloton', cat: 'Fitness' },
  { name: 'Strava', cat: 'Fitness' },
  { name: 'Whoop', cat: 'Fitness' },
  { name: 'HelloFresh', cat: 'Food' },
  { name: 'DoorDash DashPass', cat: 'Food' },
  { name: 'Uber One', cat: 'Food' },
  { name: 'YNAB', cat: 'Finance' },
  { name: 'Mint Premium', cat: 'Finance' },
  { name: 'iCloud+', cat: 'Cloud' },
  { name: 'Google One', cat: 'Cloud' },
  { name: 'Dropbox', cat: 'Cloud' },
  { name: 'OneDrive', cat: 'Cloud' },
  { name: 'Microsoft 365', cat: 'Productivity' },
  { name: 'Notion', cat: 'Productivity' },
  { name: 'Adobe Creative Cloud', cat: 'Productivity' },
  { name: 'Slack', cat: 'Productivity' },
  { name: 'ChatGPT Plus', cat: 'Productivity' },
  { name: 'GitHub Copilot', cat: 'Productivity' },
  { name: 'Canva Pro', cat: 'Productivity' },
  { name: 'LinkedIn Premium', cat: 'Productivity' },
  { name: 'Figma', cat: 'Productivity' },
  { name: 'PlayStation Plus', cat: 'Gaming' },
  { name: 'Xbox Game Pass', cat: 'Gaming' },
  { name: 'Nintendo Switch Online', cat: 'Gaming' },
  { name: 'EA Play', cat: 'Gaming' },
  { name: 'Amazon Prime', cat: 'Other' },
  { name: 'Costco Membership', cat: 'Other' },
]
